Map<String, String> cityNameConversion = {
  'Lalibela': 'ላሊበላ',
  'Bahir Dar': 'ባሕር ዳር',
  'Addis Ababa': 'አዲስ አበባ',
  'Dessie': 'ደሴ',
  'Debre Tabor': 'ደብረ ታቦር',
  'Jimma': 'ጅማ',
  'Hossaina': 'ሆሣዕና',
  'Harar': 'ሐረር',
  'Mertule Mariam': 'መርጡለ ማርያም',
  'Mekelle': 'መቀሌ',
  'Magdalena': 'መቅደላ',
  'Metema': 'መተማ',
  'Maychew': 'ማይጨው',
  'Mojo': 'ሞጆ',
  'Mota': 'ሞጣ',
  'Semera': 'ሰመራ',
  'Sodo': 'ሶዶ',
  'Shashemene': 'ሻሸመኔ',
  'Shwarobit': 'ሽዋሮቢት',
  'Koladba': 'ቆላድባ',
  'Butajira': 'ቡታጅራ',
  'Bale Robe': 'ባሌ ሮቤ',
  'Boru Meda': 'ቦሩ ሜዳ',
  'Bonga': 'ቦንጋ',
  'Boditi': 'ቦዲቲ',
  'Nekemt': 'ነቀምት',
  'Alemaya': 'አለማያ',
  'Alamata': 'አላማጣ',
  'Amber': 'አምበር',
  'Ambo': 'አምቦ',
  'Aringo': 'አሪንጎ',
  'Arsi Negele': 'አርሲ ነገሌ',
  'Arbaminch': 'አርባ ምንጭ',
  'Asosa': 'አሶሳ',
  'Ankober': 'አንኮበር',
  'Axum': 'አክሱም',
  'Awassa': 'አዋሳ',
  'Adigrat': 'አዲግራት',
  'Adama': 'አዳማ',
  'Adwa': 'አድዋ',
  'Agaro': 'አጋሮ',
  'Itbira': 'ኢትቢራ',
  'Kombolcha': 'ኮምቦልቻ',
  'Wolkite': 'ወልቂጤ',
  'Woldeya': 'ወልደያ',
  'Were ilu': 'ወረኢሉ',
  'Washera': 'ዋሸራ',
  'Yrgalem': 'ይርጋለም',
  'Dembecha': 'ደምበጫ',
  'Derba': 'ደርባ',
  'Debre Mark\'os': 'ደብረ ማርቆስ',
  'debre+markos': 'ደብረ ማርቆስ',
  'Debre Markos': 'ደብረ ማርቆስ',
  'Debre Berhan': 'ደብረ ብርሃን',
  'Debre Tabor': 'ደብረ ታቦር',
  'Debre Zeit': 'ደብረ ዘይት',
  'Degehabur': 'ደገሃቡር',
  'Dilla': 'ዲላ',
  'Dima': 'ዲማ',
  'Dera': 'ዴራ',
  'Dire Dawa': 'ድሬዳዋ',
  'Jimma': 'ጅማ',
  'Jijiga': 'ጅጅጋ',
  'Geshe Rabel': 'ጊሼ ራቤል',
  'Gambella': 'ጋምቤላ',
  'Gascha Abba Giorgis': 'ጋስጫ አባ ጊዮርጊስ',
  'Geto': 'ጌቶ',
  'Goba': 'ጎባ',
  'Gondar': 'ጎንደር',
  'Tia': 'ጢያ',
  'Finote Selam': 'ፍኖተ ሰላም'
};
List<String> specialCityNames = [
  'Debre Birhan'.toLowerCase(),
  'debre tabor'.toLowerCase(),
  'debre zeit'.toLowerCase(),
  'debre mark’os'.toLowerCase()
];
List<String> specialAmharicNames = [
  'ደብረ ብርሃን',
  'ደብረ ታቦር',
  'ደብረ ዘይት',
  'ደብረ ማርቆስ'
];
Map<String, String> weatherConditionAmharic = {
  'clear sky': 'የጠራ ሰማይ',
  'few clouds': 'ጥቂት ደመናዎች',
  'scattered clouds': 'የተበታተኑ ደመናዎች',
  'broken clouds': 'አልፎ አልፎ ደመናዎች',
  'shower rain': 'ቀላል ዝናብ',
  'rain': 'ዝናብ',
  'thunderstorm': 'ነጎድጓድ',
  'snow': 'በረዶ',
  'mist': 'ጭጋግ',
  'thunderstorm with light rain': 'ነጎድጓድ ከቀላል ዝናብ ጋር',
  'thunderstorm with rain': 'ነጎድጓድ ከዝናብ ጋር',
  'thunderstorm with heavy rain': 'ነጎድጓድ ከከባድ ዝናብ ጋር',
  'light thunderstorm': 'ቀላል ነጎድጓድ',
  'thunderstorm': 'ነጎድጓድ',
  'heavy thunderstorm': 'ከባድ ነጎድጓድ',
  'ragged thunderstorm': 'የተዝረከረከ ነጎድጓድ',
  'thunderstorm with light drizzle': 'ነጎድጓድ ከቀላል ወጨፎ ጋር',
  'thunderstorm with drizzle': 'ነጎድጓድ ዝናብ',
  'thunderstorm with heavy drizzle': 'ነጎድጓድ ከከባድ ወጨፎ ጋር',
  'light intensity drizzle': 'ወጨፎ ዝናብ',
  'drizzle': 'ወጨፎ',
  'heavy intensity drizzle': 'ከባድ ወጨፎ',
  'light intensity drizzle rain': 'ቀላል ወጨፎ',
  'drizzle rain': 'ወጨፎ ዝናብ',
  'heavy intensity drizzle rain': 'ከባድ ወጨፎ',
  'shower rain and drizzle': 'ወጨፎ ዝናብ',
  'heavy shower rain and drizzle': 'ከባድ ወጨፎ ዝናብ',
  'shower drizzle': 'ወጨፎ',
  'light rain': 'ቀላል ዝናብ',
  'moderate rain': 'መካከለኛ ዝናብ',
  'heavy intensity rain': 'ከባድ ዝናብ',
  'very heavy rain': 'በጣም ከባድ ዝናብ',
  'extreme rain': 'ከፍተኛ ዝናብ',
  'freezing rain': 'ቀዝቃዛ ዝናብ',
  'light intensity shower rain': 'ቀላል የወጨፎ ዝናብ',
  'shower rain': 'ቀላል ዝናብ',
  'heavy intensity shower rain': 'ከባድ የወጨፎ ዝናብ',
  'ragged shower rain': 'የወጨፎ ዝናብ',
  'light snow': 'ቀላል በረዶ',
  'Snow': 'በረዶ',
  'Heavy snow': 'ከባድ በረዶ',
  'Sleet': 'ዝናብ የቀላቀለ በረዶ',
  'Light shower sleet': 'ቀላል ዝናብ የቀላቀለ በረዶ',
  'Shower sleet': 'ዝናብ የቀላቀለ በረዶ',
  'Light rain and snow': 'ቀላል ዝናብ እና በረዶ',
  'Rain and snow': 'ዝናብ እና በረዶ',
  'Light shower snow': 'ቀላል ወጨፎ እና በረዶ',
  'Shower snow': 'ወጨፏማ በረዶ',
  'Heavy shower snow': 'ከባድ ወጨፏማ በረዶ',
  'mist': 'ጭጋግ',
  'Smoke': 'ጭጋግ',
  'Haze': 'ጭጋግ',
  'sand/ dust whirls': 'አሸዋ / አቧራ አዙሪት',
  'fog': 'ጭጋግ',
  'sand': 'አሸዋ',
  'dust': 'አቧራ',
  'volcanic ash': 'የእሳተ ገሞራ አመድ',
  'squalls': 'ከባድ ንፋስ',
  'tornado': 'አውሎ ንፋስ',
  'clear sky': 'የጠራ ሰማይ',
  'few clouds: 11-25%': 'ጥቂት ደመናዎች-11-25%',
  'scattered clouds': 'የተበታተኑ ደመናዎች - 25-50%',
  'broken clouds': 'ደመናዎች: 51-84%',
  'overcast clouds': 'ከመጠን በላይ ደመናዎች - 85-100%'
};
String amharicWeatherConditionProvider(String weatherCondition) {
  for (String condition in weatherConditionAmharic.keys) {
    if (equalsIgnoreCase(condition, weatherCondition))
      return weatherConditionAmharic[weatherCondition];
  }
  return weatherCondition.toUpperCase();
}

String amharicCityNameProvider(String englishName) {
  for (String name in cityNameConversion.keys) {
    if (equalsIgnoreCase(name, englishName))
      return cityNameConversion[englishName];
    else if (specialCityNames.contains(englishName.toLowerCase()))
      return specialAmharicNames[
          specialCityNames.indexOf(englishName.toLowerCase())];
  }
  return englishName.toUpperCase();
}

bool equalsIgnoreCase(String string1, String string2) {
  return string1?.toLowerCase() == string2?.toLowerCase();
}
//   List<String> amharicName = [
//     'ላሊበላ'‎,
//     'ባሕር ዳር',
//     'አዲስ አበባ',
//     'ደሴ',
//     'ደብረ ታቦር',
//     'ጅማ',
//     'ሆሣዕና',
//     'ሐረር',
//     'መርጡለ ማርያም',
//     'መቀሌ',
//     'መቅደላ',
//     'መተማ',
//     'ማይጨው',
//     'ሞጆ',
//     'ሞጣ',
//     'ሰመራ',
//     'ሶዶ',
//     'ሻሸመኔ',
//     'ሽዋሮቢት',
//     'ቆላድባ',
//     'ቡታጅራ',
//     'ባሌ ሮቤ',
//     'ቦሩ ሜዳ',
//     'ቦንጋ',
//     'ቦዲቲ',
//     'ነቀምት',
//     'አለማያ',
//     'አላማጣ',
//     'አምበር',
//     'አምቦ',
//     'አሪንጎ',
//     'አርሲ ነገሌ',
//     'አርባ ምንጭ',
//     'አሶሳ',
//     'አንኮበር',
//     'አክሱም',
//     'አዋሳ',
//     'አዲግራት',
//     'አዳማ',
//     'አድዋ',
//     'አጋሮ',
//     'ኢትቢራ',
//     'ኮምቦልቻ',
//     'ወልቂጤ',
//     'ወልወል',
//     'ወልደያ',
//     'ወረኢሉ',
//     'ዋሸራ',
//     'ይርጋለም',
//     'ደምበጫ',
//     'ደርባ',
//     'ደብረ ማርቆስ',
//     'ደብረ ብርሃን',
//     'ደብረ ታቦር',
//     'ደብረ ዘይት',
//     'ደገሃቡር',
//     'ዲላ',
//     'ዲማ',
//     'ዴራ',
//     'ድሬዳዋ',
//     'ጅማ',
//     'ጅጅጋ',
//     'ጉልጉላ',
//     'ጊሼ ራቤል',
//     'ጋምቤላ',
//     'ጋስጫ አባ ጊዮርጊስ',
//     'ጌቶ',
//     'ጎባ',
//     'ጎንደር',
//     'ጢያ',
//     'ፍኖተ ሰላም'
//   ];
//
//   List<String> egnlishName = [
//     'Lalibela',
//     'Bahir Dar',
//     'Addis Ababa',
//     'Dessie',
//     'Debre Tabor',
//     'Jimma',
//     'Hossaina',
//     'Harar',
//     'Mertule Mariam',
//     'Mekelle',
//     'Magdalena',
//     'Metema',
//     'Maychew',
//     'Mojo',
//     'Mota',
//     'Semera',
//     'Sodo',
//     'Shashemene',
//     'Shwarobit',
//     'Koladba',
//     'Butajira',
//     'Bale Robe',
//     'Boru Meda',
//     'Bonga',
//     'Bodi',
//     'Nekemt',
//     'Alemaya',
//     'Alamata',
//     'Amber',
//     'Ambo',
//     'Aringo',
//     'Arsi Negele',
//     'Arbaminch',
//     'Asosa',
//     'Ankober',
//     'Axum',
//     'Awassa',
//     'Adigrat',
//     'Adama',
//     'Adwa',
//     'Agaro',
//     'Itbira',
//     'Kombolcha',
//     'Wolkite',
//     'Woldeya',
//     'Were ilu',
//     'Washera',
//     'Yrgalem',
//     'Dembecha',
//     'Derba',
//     'Debre Markos',
//     'Debre Berhan',
//     'Debre Tabor',
//     'Debre Zeit',
//     'Degehabur',
//     'Dilla',
//     'Dima',
//     'Dera',
//     'Dire Dawa',
//     'Jimma',
//     'Jijiga',
//     'Geshe Rabel',
//     'Gambella',
//     'Gascha Abba Giorgis',
//     'Geto',
//     'Goba',
//     'Gondar',
//     'Tia',
//     'Finote Selam'
//   ];
// }
// String changer(String s) {
//   s.toLowerCase();
//   if ((s == 'debre mark’os')) return 'ደብረ ማርቆስ';
//   if ((s == 'Debre Birhan'.toLowerCase())) return 'ደብረ ብርሃን';
//   if ((s == 'debre tabor')) return 'ደብረ ታቦር';
//   if ((s == 'debre zeit'))
//     return 'ደብረ ዘይት';
//   else
//     return s;
// }
